enh: address almost all Bandit security annotations (#3441)
* chore(ci): move all linter options into pyproject.toml and remove almost all global Bandit rule exceptions. pyupgrade itself does not support pyproject.toml. There is pyproject-pyupgrade, which however has not seen any commit since 2 years. We just support both now.
* linux_init has been hardened via `set -e`, a `mktemp -d` path for the motion package download, and support for single-line JSON GitHub API responses, returned by some of their servers.
* `tasks.start()` has been hardened to load tasks and init the multiprocessing pool before scheduling the handler loop.
* `tasks.stop()` does now stop the handler loop, instead of letting it run into exceptions. And it properly closes the multiprocessing pool, letting running tasks finish, blocking the main thread. This means, that stopping motionEye will wait for potentially movie preview generation and media uploads to finish, instead of terminating them.
* `utils.urlopen()` supports only http/https requests now, and takes only a single positional Request argument (aside of the keyword args), matching how it is used across our code. The URL scheme limitation only affects webhooks, where a custom URL scheme is currently possible, but likely unnecessary.
* The SMB module does not check for and cache `mount.cifs` and `umount` executable paths, instead of running them without full path.
* The timezone module has been fixed: The `/etc/localtime` symlink resolution failed in case of relative symlinks, common for e.g. UTC (`/usr/share/zoneinfo/UTC` -> `Etc/UTC`). And the MD5 method, used if `/etc/localtime` is an actual file, never worked, because of a false early exit logic.
* PID and log paths are not initialized as `/tmp` or `/var/tmp` anymore. Those directories are usually world-writable, hence prone to malicious symlinks. Especially if motionEye starts as root (which it should not do), this can be dangerous. Our default config and systemd unit sets up properly owned subdirs, which is what any setup should do.

Signed-off-by: MichaIng <micha@dietpi.com>

diff --git a/motioneye/extra/linux_init b/motioneye/extra/linux_init
--- a/motioneye/extra/linux_init
+++ b/motioneye/extra/linux_init
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 
+set -e
+
 if (( UID )); then
-  echo 'ERROR: Root permissions required. Please run this command as root user, via "sudo" or "su". Aborting...'
+  echo 'ERROR: Root permissions required. Please run this command as root user, via "sudo" or "su". Aborting ...'
   exit 1
 fi
 
@@ -12,7 +14,7 @@ while (( $# )); do
   case "$1" in
     '--skip-systemd') SKIP_SYSTEMD=1;;
     '--skip-apt-update') SKIP_APT_UPDATE=1;;
-    *) echo "ERROR: Invalid command-line argument \"$1\". Aborting..."; exit 1;;
+    *) echo "ERROR: Invalid command-line argument \"$1\". Aborting ..."; exit 1;;
   esac
   shift
 done
@@ -24,6 +26,7 @@ if command -v apt-get > /dev/null; then
   # If matching package can be found, install from motion project GitHub releases
   MOTION='motion'
   DISTRO=''
+  TMPDIR=''
   [[ -f '/etc/os-release' ]] && DISTRO=$(sed -n '/^VERSION_CODENAME=/{s/^[^=]*=//p;q}' /etc/os-release)
   if [[ $DISTRO ]]; then
     ARCH=$(dpkg --print-architecture)
@@ -31,14 +34,15 @@ if command -v apt-get > /dev/null; then
     PI=''
     [[ ${ARCH} == 'armhf' && $(uname -m) == 'armv6l' ]] && PI='pi_'
     echo "INFO: ${DISTRO^} on ${ARCH} detected, checking for latest motion package from GitHub releases"
-    command -v curl > /dev/null || DEBIAN_FRONTEND="noninteractive" apt-get -y --no-install-recommends install curl
-    URL=$(curl -sSfL 'https://api.github.com/repos/Motion-Project/motion/releases' | awk -F\" "/browser_download_url.*${PI}${DISTRO}_motion_.*_${ARCH}.deb/{print \$4}" | head -1)
+    command -v curl > /dev/null || DEBIAN_FRONTEND='noninteractive' apt-get -y --no-install-recommends install curl
+    URL=$(curl -sSfL 'https://api.github.com/repos/Motion-Project/motion/releases' | grep -Po "\"browser_download_url\": *\"\K[^\"]*\/${PI}${DISTRO}_motion_.*_${ARCH}\.deb(?=\")" | head -1)
     if [[ ${URL} ]]
     then
       echo "INFO: Matching package found, downloading: ${URL}"
-      if curl -fLo /tmp/motion.deb "${URL}"
+      TMPDIR=$(mktemp -d)
+      if curl -fLo "${TMPDIR}/motion.deb" "${URL}"
       then
-        MOTION='/tmp/motion.deb'
+        MOTION="${TMPDIR}/motion.deb"
       else
         echo 'WARNING: Download failed, installing (older) motion package from APT repository instead'
       fi
@@ -48,8 +52,8 @@ if command -v apt-get > /dev/null; then
   else
     echo 'WARNING: Distribution version could not be detected, installing motion from APT repository'
   fi
-  DEBIAN_FRONTEND="noninteractive" apt-get -y --no-install-recommends install "${MOTION}" v4l-utils ffmpeg curl
-  rm -f motion.deb
+  DEBIAN_FRONTEND='noninteractive' apt-get -y --no-install-recommends install "${MOTION}" v4l-utils ffmpeg curl
+  [[ $TMPDIR ]] && rm -R "$TMPDIR"
 elif command -v yum > /dev/null; then
   echo 'INFO: YUM-based distribution detected, installing motionEye dependencies'
   yum -y install motion v4l-utils ffmpeg curl
@@ -81,8 +85,7 @@ cp extra/motioneye.systemd /etc/systemd/system/motioneye.service
 # - Update meyectl path if expected /usr/local/bin/meyectl does not exist, found on Arch Linux: https://github.com/motioneye-project/motioneye/issues/3005
 if [[ ! -f '/usr/local/bin/meyectl' ]]
 then
-  meyectl_path=$(command -v meyectl)
-  if [[ $meyectl_path ]]
+  if meyectl_path=$(command -v meyectl)
   then
     echo "Using $meyectl_path for systemd service"
     sed -i "s|^ExecStart=/usr/local/bin/meyectl|ExecStart=$meyectl_path|" /etc/systemd/system/motioneye.service
